### ISSUE TITLE
User can search for organizations looking for donation

### ISSUE THREAD

**Issue by user512** [vikramrojo/emergency.fyi#3]
Wonder if it's a good idea to have a tab dedicated to show organizations that is looking for donation, happy to contribute.

Something like this, and user can further filter organizations by target groups (Like donation to retail worker/ medical worker/ researcher)
<img width="851" alt="Screen Shot 2020-03-23 at 10 46 37 PM" src="https://user-images.githubusercontent.com/8117421/77392464-40353580-6d58-11ea-8824-6ddeb6ed6046.png">

**Comment by vikramrojo** [comment]
Donations sounds like a great idea.

**Comment by user512** [comment]
Great @atav1k, cloning the repo to play around with it. If you have any thoughts on how the donation page should be structure, please let me know.

**Comment by vikramrojo** [comment]
i would probably make it similar to the index.json & _posts.js fetch structure. that way i can make another airtable base but for donations.

**Comment by vikramrojo** [comment]
made you a collaborator so it's easier.

**Comment by user512** [comment]
Resolved by https://github.com/atav1k/emergency.fyi/pull/4
